### ISSUE TITLE
Cannot read peas.json from skyscraper config folder

### ISSUE THREAD

**Issue by josegonzalez** [boxart-buddy/boxart-buddy#2]
I just setup the project using the quickstart guide and it's erroring out immediately when running `make scrape`:

```
boxart-buddy % make scrape
php bin/console scrape

██████╗  ██████╗ ██╗  ██╗ █████╗ ██████╗ ████████╗    ██████╗ ██╗   ██╗██████╗ ██████╗ ██╗   ██╗
██╔══██╗██╔═══██╗╚██╗██╔╝██╔══██╗██╔══██╗╚══██╔══╝    ██╔══██╗██║   ██║██╔══██╗██╔══██╗╚██╗ ██╔╝
██████╔╝██║   ██║ ╚███╔╝ ███████║██████╔╝   ██║       ██████╔╝██║   ██║██║  ██║██║  ██║ ╚████╔╝
██╔══██╗██║   ██║ ██╔██╗ ██╔══██║██╔══██╗   ██║       ██╔══██╗██║   ██║██║  ██║██║  ██║  ╚██╔╝
██████╔╝╚██████╔╝██╔╝ ██╗██║  ██║██║  ██║   ██║       ██████╔╝╚██████╔╝██████╔╝██████╔╝   ██║
╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝       ╚═════╝  ╚═════╝ ╚═════╝ ╚═════╝    ╚═╝


In RomExtensionProvider.php line 57:

  Cannot read peas.json from skyscraper config folder


prime-cache

make: *** [scrape] Error 1
```

```
$ php -v
PHP 8.3.9 (cli) (built: Jul  2 2024 14:10:14) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.9, Copyright (c), by Zend Technologies
```

With the following version cloned:

```
% git show
commit bd8946c53aa9735c55bbabfbafbc7a1b832b30cd (HEAD -> main, origin/main, origin/HEAD)
```

```
 % ls -lah user_config
total 56
drwxrwxrwx@  8 josediazgonzalez  staff   256B Jul  7 17:21 .
drwxr-xr-x@ 41 josediazgonzalez  staff   1.3K Jul  7 17:21 ..
-rw-rw-rw-@  1 josediazgonzalez  staff   848B Jul  7 17:25 config.yml
-rw-rw-rw-@  1 josediazgonzalez  staff   1.7K Jul  7 17:27 config_platform.yml
-rw-rw-rw-@  1 josediazgonzalez  staff   240B Jul  7 17:21 config_portmaster.yml
-rw-rw-rw-@  1 josediazgonzalez  staff   2.2K Jul  7 17:21 folder_roms.yml
-rw-rw-rw-@  1 josediazgonzalez  staff   1.6K Jul  7 17:21 name_extra.json
-rw-rw-rw-@  1 josediazgonzalez  staff   6.3K Jul  7 17:21 rom_translations.yml
```

Is there a file that I should create/what should it's contents be?

**Comment by boxart-buddy** [comment]
Hi,

This error is being produced by Skyscraper rather than this project, it suggests an issue with the way skyscraper has been installed.

Do you have the file:

~/.skyscraper/peas.json

Did you freshly install a copy of skyscraper from:
https://github.com/Gemba/Skyscraper/

**Comment by boxart-buddy** [comment]
@josegonzalez actually this was slightly incorrect, the error is being generated by this application but the root cause is still the same, an issue with skyscraper installation folder.

Have you used the default config.yml value:

skyscraper_config_folder_path: '~/.skyscraper'

and does that folder contain 'peas.json'?

**Comment by josegonzalez** [comment]
Apologies for the lack of response (was afk). The path `skyscraper_config_folder_path` is not set in my config.yml so I assume it uses the default. That said, I have no `peas.json` in that path (though the path does exist).

**Comment by boxart-buddy** [comment]
@josegonzalez no worries.

I'm wondering if that file only generates the first time skyscraper is run - its hard for me to test that.
Try a fresh install of this fork: https://github.com/Gemba/Skyscraper/

Let me know if that doesn't fix things - I can run a fresh install of everything in a VM and figure it out (lmk what os/distro you are using as well)

**Comment by boxart-buddy** [comment]
Also the path for peas.json should be:

~/.skyscraper/peas.json

**Comment by josegonzalez** [comment]
I'll be able to test this out tonight, but for reference, I'm on an m2 Macbook Pro running Sonoma 14.5.

**Comment by boxart-buddy** [comment]
> I'll be able to test this out tomorrow night, but for reference, I'm on an m2 Macbook Pro running Sonoma 14.5.

Same hardware/software as me.

If you run just:

```Skyscraper```

And the output is:

```
File not found 'peas.json'. Now quitting...
```

Then it suggests an issue with the install
